theme: jekyll-theme-minimal

title: Jianping Fu
description: I'm an assistant professor of mathematics at Tianjin University of Techonology, and I received my Ph.D. from Nankai University under the supervision of professor Yongjin Wang.
